platform-pair: Add more concise words and improve no network behavior
Before if the device was turned on without an internet connection,
it will be blinking the image without any indication of the issue.
The user would have to login into the device to then check the logs.
Now we added a retry mechanism and an annotation on the image to
indicate that there is no network connection.

Signed-off-by: Matheus Castello <matheus@castello.eng.br>

diff --git a/cookbook/recipes-toradex/platform-pair-fb/pair-fb b/cookbook/recipes-toradex/platform-pair-fb/pair-fb
--- a/cookbook/recipes-toradex/platform-pair-fb/pair-fb
+++ b/cookbook/recipes-toradex/platform-pair-fb/pair-fb
@@ -40,9 +40,34 @@ sleep 10s
 
 ping -c 1 8.8.8.8 > /dev/null 2>&1
 if [ $? -ne 0 ]; then
-    echo "Error: No internet connection. Please check your network settings." >&2
-    exit 69
+    echo "No internet connection. Retrying..." >&2
+
+    # Annotate the image with error message
+    cp /usr/share/pair-fb/diagrams.jpg /home/phobos/back.jpg
+    convert \
+        /home/phobos/back.jpg \
+        -gravity SouthWest \
+        -pointsize 100 \
+        -fill red \
+        -gravity NorthWest \
+        -annotate 0x0+1029+570 \
+        "No Network" \
+        /home/phobos/output.jpg
 fi
+
+# Wait for internet connection with retries
+while true; do
+    ping -c 1 8.8.8.8 > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        # Internet is available, break out of the loop
+        break
+    fi
+
+    echo "No internet connection. Retrying..." >&2
+
+    # Wait before retrying
+    sleep 10s
+done
 
 ret=$(curl -fsSL "https://app.torizon.io/api/provision-code")
 
